// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using Azure.Core;

namespace Microsoft.Marketplace.Metering
{
    /// <summary> Client options for Metering. </summary>
    public class MarketplaceMeteringClientOptions
        : ClientOptions
    {
    }
}
