// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using Azure.Core;
using Azure.Core.Pipeline;
using Microsoft.Marketplace.Metering;

namespace Microsoft.Marketplace.Metering
{
    /// <summary> Metering service management client. </summary>
    public class MeteringManagementClient
    {
        private readonly ClientDiagnostics _clientDiagnostics;
        private readonly HttpPipeline _pipeline;
        private readonly Uri _endpoint;

        /// <summary> Initializes a new instance of MeteringManagementClient for mocking. </summary>
        protected MeteringManagementClient()
        {
        }

        /// <summary> Initializes a new instance of MeteringManagementClient. </summary>
        /// <param name="tokenCredential"> The OAuth token for making client requests. </param>
        /// <param name="options"> The options for configuring the client. </param>
        public MeteringManagementClient(TokenCredential tokenCredential, MeteringManagementClientOptions options = null) : this(null, tokenCredential, options)
        {
        }
        /// <summary> Initializes a new instance of MeteringManagementClient. </summary>
        /// <param name="endpoint"> server parameter. </param>
        /// <param name="tokenCredential"> The OAuth token for making client requests. </param>
        /// <param name="options"> The options for configuring the client. </param>
        public MeteringManagementClient(Uri endpoint, TokenCredential tokenCredential, MeteringManagementClientOptions options = null)
        {
            endpoint ??= new Uri("https://marketplaceapi.microsoft.com/api");

            options ??= new MeteringManagementClientOptions();
            _clientDiagnostics = new ClientDiagnostics(options);
            _pipeline = ManagementPipelineBuilder.Build(tokenCredential, endpoint, options);
            _endpoint = endpoint;
        }

        /// <summary> Returns an instance of MeteringOperations. </summary>
        public virtual MeteringOperations Metering => new MeteringOperations(_clientDiagnostics, _pipeline, _endpoint);
    }
}
