FROM ubuntu:xenial 

LABEL maintainer="Microsoft" 

# Required for install
RUN apt-get update && apt-get install -y curl libunwind8 libicu55

# NodeJS
RUN curl -sL https://deb.nodesource.com/setup_13.x | bash - && \
	apt-get update && apt-get install -y nodejs && \
	npm install npm@latest -g 

# Being utilities in
RUN apt-get update && apt-get install -y git

# Autorest
RUN npm install -g autorest@latest
RUN autorest --reset 

# Set the locale to UTF-8
RUN apt-get clean && apt-get update && apt-get install -y locales
RUN locale-gen en_US.UTF-8  
ENV LANG en_US.UTF-8  
ENV LANGUAGE en_US:en  
ENV LC_ALL en_US.UTF-8  

RUN git clone https://github.com/Azure/azure-marketplace-openapi.git

ENTRYPOINT [ "/bin/bash", "-c", "npx autorest ./azure-marketplace-openapi/$SDK/autorest.md --v3 --csharp --csharp-sdks-folder=/out  --add-credentials" ] 
