// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using Azure.Core;

namespace Microsoft.Marketplace.SaaS
{
    /// <summary> Client options for SaaS. </summary>
    public class MarketplaceSaaSClientOptions : ClientOptions
    {
    }
}
