// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using Azure.Core;
using Azure.Core.Pipeline;
using Microsoft.Marketplace.SaaS;

namespace Microsoft.Marketplace.SaaS
{
    /// <summary> SaaS service management client. </summary>
    public class MarketplaceSaaSClient
    {
        private readonly ClientDiagnostics _clientDiagnostics;
        private readonly HttpPipeline _pipeline;
        private readonly Uri _endpoint;

        /// <summary> Initializes a new instance of SaaSManagementClient for mocking. </summary>
        protected MarketplaceSaaSClient()
        {
        }

        /// <summary> Initializes a new instance of SaaSManagementClient. </summary>
        /// <param name="tokenCredential"> The OAuth token for making client requests. </param>
        /// <param name="options"> The options for configuring the client. </param>
        public MarketplaceSaaSClient(TokenCredential tokenCredential, MarketplaceSaaSClientOptions options = null) : this(null, tokenCredential, options)
        {
        }
        /// <summary> Initializes a new instance of SaaSManagementClient. </summary>
        /// <param name="endpoint"> server parameter. </param>
        /// <param name="tokenCredential"> The OAuth token for making client requests. </param>
        /// <param name="options"> The options for configuring the client. </param>
        public MarketplaceSaaSClient(Uri endpoint, TokenCredential tokenCredential, MarketplaceSaaSClientOptions options = null)
        {
            endpoint ??= new Uri("https://marketplaceapi.microsoft.com/api");

            options ??= new MarketplaceSaaSClientOptions();
            _clientDiagnostics = new ClientDiagnostics(options);
            _pipeline = HttpPipelineBuilder.Build(options, new BearerTokenAuthenticationPolicy(tokenCredential, $"20e940b3-4c77-4b0b-9a53-9e16a1b010a7/.default"));
            _endpoint = endpoint;
        }

        /// <summary> Returns an instance of FulfillmentOperations. </summary>
        public virtual FulfillmentOperations Fulfillment => new FulfillmentOperations(_clientDiagnostics, _pipeline, _endpoint);

        /// <summary> Returns an instance of SubscriptionOperations. </summary>
        public virtual SubscriptionOperations SubscriptionOperations => new SubscriptionOperations(_clientDiagnostics, _pipeline, _endpoint);
    }
}
